### ISSUE TITLE
Ransomware Note

### ISSUE THREAD

**Issue by ParkerNC** [ParkerNC/Ransomware#2]
After encryption, display ransomware note, probably by spawning a dialogue box or terminal. Bitcoin for now.

**Comment by ParkerNC** [comment]
the code needs to know when it has already encrypted the files in the case of the script crashing

**Comment by taha59** [comment]
The window opens as soon as the client thread connects. Once the window opens, a textbox is shown to the victim for them to put their bitcoin payment in. The victim has to click the submit button and close window for the attacker to receive payment.
